### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by younheera** [beomsun1234/spring-openbanking-kotlin#2]
안녕하세요. 현재 자바기반으로 핀테크 웹개발 프로젝트 진행 중인 사람입니다.
급작스럽게 댓글 남겨 놀라셨겠지만.. 자료가 많지않아 서칭 중에 해당 깃에 와서 질문 남깁니다.
혹시 금융결제원 오픈API이용하셔서 구현 완성하셨을까요??
금융결제원 문의한 결과 법인사업자등록이 있어야 접근가능하다고 해서 개발과정 중에 진행이 되지않고 있는 상황입니다.
혹시 어떻게 접근하셔서 구현하셨을지 궁금하여 댓글 남깁니다.

**Comment by beomsun1234** [comment]
안녕하세요! 우선 spring boot + java 를 이용해서는 구현은 완성했습니다. https://github.com/beomsun1234/spring-openbanking, 법인사업자가 아닌 일반 사용자들은 테스트 데이터만 가지고 이용가능 합니다. 저도 일반 사용자라 테스트 데이터에만 접근가능하고 오픈뱅킹 개발자 사이트에 '문서', '도구' 메뉴에 있는 자료를 가지고 구현했습니다!
